fix: python version, redundant output code, use string literal
according to brew audit
❯ brew audit naokiiida/42/c_formatter_42
  * line 24, col 71: Passing 0 to shell_output() is redundant
  * Dependency 'python' does not define option ">=3.8"
Error: 2 problems in 1 formula detected.
❯ brew audit naokiiida/42/norminette
  * line 18, col 76: Passing 0 to shell_output() is redundant
  * line 19, col 32: Use an empty string literal instead of heredoc.
  * Dependency 'python' does not define option ">=3.8"
Error: 3 problems in 1 formula detected.